use std::hash::{Hash, Hasher};
use std::io::{Read, Seek};

use log::{debug, trace};
use zip::read::ZipArchive;

use super::content_types::ContentTypes;
use super::error::{Error, Result};
use super::relationships::{Relationships, rel_types};

// ---------------------------------------------------------------------------
// PartName
// ---------------------------------------------------------------------------

/// A validated, normalized OPC part name.
///
/// Part names always start with '/' and are compared case-insensitively per OPC §5.
#[derive(Debug, Clone)]
pub struct PartName(String);

/// Decode percent-encoded UTF-8 sequences (e.g., `%C3%A1` → `á`).
fn decode_percent_encoding(input: &str) -> String {
    let bytes = input.as_bytes();
    let mut decoded = Vec::with_capacity(bytes.len());
    let mut i = 0;
    while i < bytes.len() {
        if bytes[i] == b'%' && i + 2 < bytes.len() {
            if let (Some(hi), Some(lo)) = (hex_digit(bytes[i + 1]), hex_digit(bytes[i + 2])) {
                decoded.push(hi << 4 | lo);
                i += 3;
                continue;
            }
        }
        decoded.push(bytes[i]);
        i += 1;
    }
    String::from_utf8(decoded).unwrap_or_else(|_| input.to_string())
}

fn hex_digit(b: u8) -> Option<u8> {
    match b {
        b'0'..=b'9' => Some(b - b'0'),
        b'a'..=b'f' => Some(b - b'a' + 10),
        b'A'..=b'F' => Some(b - b'A' + 10),
        _ => None,
    }
}

impl PartName {
    /// Validate and create a new PartName per OPC part naming rules.
    /// Percent-encoded sequences are decoded before validation (tolerant parsing
    /// for files generated by LibreOffice which incorrectly percent-encodes non-ASCII).
    pub fn new(name: &str) -> Result<Self> {
        // Decode percent-encoding if present (tolerant of non-spec-compliant producers)
        let name = if name.contains('%') {
            decode_percent_encoding(name)
        } else {
            name.to_string()
        };

        // Must start with '/'
        if !name.starts_with('/') {
            return Err(Error::InvalidPartName(format!(
                "must start with '/': {name}"
            )));
        }
        // Must not end with '/'
        if name.len() > 1 && name.ends_with('/') {
            return Err(Error::InvalidPartName(format!(
                "must not end with '/': {name}"
            )));
        }
        // No empty segments (//)
        if name.contains("//") {
            return Err(Error::InvalidPartName(format!(
                "empty segment (//): {name}"
            )));
        }
        // No dot segments
        for segment in name.split('/').skip(1) {
            if segment == "." || segment == ".." {
                return Err(Error::InvalidPartName(format!(
                    "dot segment not allowed: {name}"
                )));
            }
            // Segments must not end with '.'
            if segment.ends_with('.') {
                return Err(Error::InvalidPartName(format!(
                    "segment ends with dot: {name}"
                )));
            }
        }
        // No query/fragment
        if name.contains('?') || name.contains('#') {
            return Err(Error::InvalidPartName(format!(
                "query/fragment not allowed: {name}"
            )));
        }
        // No backslashes
        if name.contains('\\') {
            return Err(Error::InvalidPartName(format!(
                "backslash not allowed: {name}"
            )));
        }

        Ok(Self(name))
    }

    /// Return the part name as a string slice (always starts with `/`).
    pub fn as_str(&self) -> &str {
        &self.0
    }

    /// Extract the file extension (without leading dot), if any.
    pub fn extension(&self) -> Option<&str> {
        let filename = self.filename();
        filename.rfind('.').map(|i| &filename[i + 1..])
    }

    /// The directory portion, e.g. "/word/" for "/word/document.xml".
    pub fn directory(&self) -> &str {
        match self.0.rfind('/') {
            Some(i) => &self.0[..=i],
            None => "/",
        }
    }

    /// The filename portion, e.g. "document.xml" for "/word/document.xml".
    pub fn filename(&self) -> &str {
        match self.0.rfind('/') {
            Some(i) => &self.0[i + 1..],
            None => &self.0,
        }
    }

    /// Compute the path to this part's relationships file.
    /// e.g. "/word/document.xml" -> "/word/_rels/document.xml.rels"
    pub fn rels_path(&self) -> String {
        let dir = self.directory();
        let file = self.filename();
        format!("{dir}_rels/{file}.rels")
    }

    /// Resolve a relative URI against this part name's directory.
    pub fn resolve_relative(&self, relative: &str) -> Result<PartName> {
        if relative.starts_with('/') {
            // Absolute path
            return PartName::new(relative);
        }

        let base = self.directory();
        let combined = format!("{base}{relative}");

        // Normalize path by resolving .. and .
        let normalized = normalize_path(&combined);
        PartName::new(&normalized)
    }
}

/// Case-insensitive equality per OPC spec §5.
impl PartialEq for PartName {
    fn eq(&self, other: &Self) -> bool {
        self.0.eq_ignore_ascii_case(&other.0)
    }
}

impl Eq for PartName {}

/// Case-insensitive hashing to match case-insensitive equality.
impl Hash for PartName {
    fn hash<H: Hasher>(&self, state: &mut H) {
        for byte in self.0.bytes() {
            state.write_u8(byte.to_ascii_lowercase());
        }
    }
}

impl std::fmt::Display for PartName {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.0)
    }
}

/// Normalize a path by resolving `.` and `..` segments.
fn normalize_path(path: &str) -> String {
    let mut segments: Vec<&str> = Vec::new();
    for segment in path.split('/') {
        match segment {
            "." | "" => {
                // Skip empty (from leading slash or //) and current-dir refs
                if segments.is_empty() {
                    segments.push(""); // preserve leading slash
                }
            }
            ".." => {
                // Go up one level, but don't go above root
                if segments.len() > 1 {
                    segments.pop();
                }
            }
            s => segments.push(s),
        }
    }
    if segments.len() == 1 && segments[0].is_empty() {
        return "/".to_string();
    }
    segments.join("/")
}

// ---------------------------------------------------------------------------
// OpcReader
// ---------------------------------------------------------------------------

/// Reader for OPC (Open Packaging Conventions) packages (ZIP-based).
pub struct OpcReader<R: Read + Seek> {
    archive: ZipArchive<R>,
    content_types: ContentTypes,
    package_rels: Relationships,
}

impl<R: Read + Seek> OpcReader<R> {
    /// Create an OPC reader from any `Read + Seek` source.
    pub fn new(reader: R) -> Result<Self> {
        let mut archive = ZipArchive::new(reader)?;
        crate::budget::check_zip_entries(archive.len()).map_err(map_budget_error)?;
        let mut entry_names = std::collections::HashSet::with_capacity(archive.len());
        for name in archive.file_names() {
            let normalized = name.replace('\\', "/");
            if normalized.starts_with('/')
                || normalized.split('/').any(|segment| segment == "..")
                || !entry_names.insert(normalized)
            {
                return Err(Error::InvalidPartName(
                    "invalid or duplicate ZIP entry".to_owned(),
                ));
            }
        }
        debug!("OPC package opened, {} entries", archive.len());

        // Eagerly parse [Content_Types].xml
        let ct_data = read_zip_entry(&mut archive, "[Content_Types].xml")?;
        crate::budget::validate_xml(&ct_data).map_err(map_budget_error)?;
        let content_types = ContentTypes::parse(&ct_data)?;

        // Eagerly parse _rels/.rels
        let rels_data = match read_zip_entry(&mut archive, "_rels/.rels") {
            Ok(data) => data,
            Err(Error::Zip(zip::result::ZipError::FileNotFound) | Error::MissingPart(_)) => {
                Vec::new()
            }
            Err(error) => return Err(error),
        };
        let package_rels = if rels_data.is_empty() {
            Relationships::empty()
        } else {
            crate::budget::validate_xml(&rels_data).map_err(map_budget_error)?;
            Relationships::parse(&rels_data)?
        };

        Ok(Self {
            archive,
            content_types,
            package_rels,
        })
    }

    /// Return the parsed `[Content_Types].xml` table.
    pub fn content_types(&self) -> &ContentTypes {
        &self.content_types
    }

    /// Read a part's raw bytes.
    /// XML parts with non-UTF-8 encoding declarations are automatically transcoded to UTF-8.
    pub fn read_part(&mut self, name: &PartName) -> Result<Vec<u8>> {
        let zip_path = &name.as_str()[1..]; // strip leading /
        let data = read_zip_entry(&mut self.archive, zip_path)?;
        trace!("read_part '{}' ({} bytes)", name, data.len());

        // Transcode non-UTF-8 XML to UTF-8 (handles ISO-8859-1, Windows-1252, etc.)
        let data = if name.as_str().ends_with(".xml") || name.as_str().ends_with(".rels") {
            if let Some(utf8_data) = super::xml::ensure_utf8(&data) {
                trace!("read_part '{name}': transcoded to UTF-8");
                utf8_data
            } else {
                data
            }
        } else {
            data
        };
        if name.as_str().ends_with(".xml") || name.as_str().ends_with(".rels") {
            crate::budget::validate_xml(&data).map_err(map_budget_error)?;
        }
        Ok(data)
    }

    /// Read and parse the relationships for a given part.
    pub fn read_rels_for(&mut self, part: &PartName) -> Result<Relationships> {
        let rels_zip_path = part.rels_path();
        let zip_path = &rels_zip_path[1..]; // strip leading /
        match read_zip_entry(&mut self.archive, zip_path) {
            Ok(data) => {
                crate::budget::validate_xml(&data).map_err(map_budget_error)?;
                trace!("read_rels_for '{}' ({} bytes)", part, data.len());
                Relationships::parse(&data)
            }
            Err(Error::Zip(zip::result::ZipError::FileNotFound)) => {
                trace!("read_rels_for '{part}': no rels file");
                Ok(Relationships::empty())
            }
            Err(Error::MissingPart(_)) => {
                trace!("read_rels_for '{part}': no rels file");
                Ok(Relationships::empty())
            }
            Err(e) => Err(e),
        }
    }

    /// Find the main document part via the officeDocument relationship.
    /// Falls back to scanning `[Content_Types].xml` overrides when `_rels/.rels` is
    /// missing or corrupted.
    pub fn main_document_part(&self) -> Result<PartName> {
        // Primary: use the officeDocument relationship from _rels/.rels
        if let Some(rel) = self.package_rels.first_by_type(rel_types::OFFICE_DOCUMENT) {
            if rel.target_mode != super::relationships::TargetMode::Internal {
                return Err(Error::MalformedXml(
                    "officeDocument relationship must be internal".to_owned(),
                ));
            }
            let target = if rel.target.starts_with('/') {
                rel.target.clone()
            } else {
                format!("/{}", rel.target)
            };
            return PartName::new(&target);
        }

        // Fallback: scan [Content_Types].xml overrides for a main document content type
        const MAIN_CONTENT_TYPES: &[&str] = &[
            "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml",
            "application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml",
            "application/vnd.openxmlformats-officedocument.presentationml.presentation.main+xml",
        ];
        for (part_name, ct) in self.content_types.overrides() {
            if MAIN_CONTENT_TYPES.iter().any(|&expected| ct == expected) {
                debug!(
                    "main_document_part: fallback to Content_Types override '{part_name}' ({ct})"
                );
                return Ok(part_name.clone());
            }
        }

        Err(Error::RelationshipNotFound(
            "officeDocument relationship not found".to_string(),
        ))
    }
}

/// Read a ZIP entry by name, returning its bytes.
/// Falls back to case-insensitive and backslash-normalized lookup if exact match fails.
pub(crate) fn read_zip_entry<R: Read + Seek>(
    archive: &mut ZipArchive<R>,
    name: &str,
) -> Result<Vec<u8>> {
    crate::budget::check_cancelled().map_err(map_budget_error)?;
    let index = archive
        .index_for_name(name)
        .ok_or_else(|| Error::MissingPart(name.to_string()))?;
    let mut file = archive.by_index(index).map_err(Error::from)?;
    crate::budget::check_zip_part(file.size()).map_err(map_budget_error)?;
    crate::budget::check_zip_compression_ratio(file.compressed_size(), file.size())
        .map_err(map_budget_error)?;
    let capacity = usize::try_from(file.size()).map_err(|_| Error::ResourceLimit {
        resource: "office_zip_part_bytes",
        limit: usize::MAX as u64,
        observed: file.size(),
    })?;
    let mut buf = Vec::with_capacity(capacity);
    let mut chunk = [0_u8; 64 * 1024];
    loop {
        crate::budget::check_cancelled().map_err(map_budget_error)?;
        let read = file.read(&mut chunk)?;
        if read == 0 {
            break;
        }
        let observed = buf.len().saturating_add(read) as u64;
        crate::budget::charge_zip_growth(file.size(), observed).map_err(map_budget_error)?;
        buf.extend_from_slice(&chunk[..read]);
    }
    crate::budget::charge_zip_part(buf.len() as u64).map_err(map_budget_error)?;
    Ok(buf)
}

fn map_budget_error(error: crate::OfficeReadError) -> Error {
    match error {
        crate::OfficeReadError::ResourceLimit {
            resource,
            limit,
            observed,
        } => Error::ResourceLimit {
            resource,
            limit,
            observed,
        },
        crate::OfficeReadError::Cancelled => Error::Cancelled,
        _ => Error::Cancelled,
    }
}
