use super::*;

/// Standard CFF string IDs (SIDs) 0-390 per CFF specification Table A-2.
/// Only the subset needed for encoding (common glyph names).
pub(super) fn sid_to_name(sid: u16) -> Option<&'static str> {
    // CFF predefined strings (SID 0-390)
    // Full table from Adobe CFF specification, Appendix A
    static SID_NAMES: &[&str] = &[
        ".notdef",             // 0
        "space",               // 1
        "exclam",              // 2
        "quotedbl",            // 3
        "numbersign",          // 4
        "dollar",              // 5
        "percent",             // 6
        "ampersand",           // 7
        "quoteright",          // 8
        "parenleft",           // 9
        "parenright",          // 10
        "asterisk",            // 11
        "plus",                // 12
        "comma",               // 13
        "hyphen",              // 14
        "period",              // 15
        "slash",               // 16
        "zero",                // 17
        "one",                 // 18
        "two",                 // 19
        "three",               // 20
        "four",                // 21
        "five",                // 22
        "six",                 // 23
        "seven",               // 24
        "eight",               // 25
        "nine",                // 26
        "colon",               // 27
        "semicolon",           // 28
        "less",                // 29
        "equal",               // 30
        "greater",             // 31
        "question",            // 32
        "at",                  // 33
        "A",                   // 34
        "B",                   // 35
        "C",                   // 36
        "D",                   // 37
        "E",                   // 38
        "F",                   // 39
        "G",                   // 40
        "H",                   // 41
        "I",                   // 42
        "J",                   // 43
        "K",                   // 44
        "L",                   // 45
        "M",                   // 46
        "N",                   // 47
        "O",                   // 48
        "P",                   // 49
        "Q",                   // 50
        "R",                   // 51
        "S",                   // 52
        "T",                   // 53
        "U",                   // 54
        "V",                   // 55
        "W",                   // 56
        "X",                   // 57
        "Y",                   // 58
        "Z",                   // 59
        "bracketleft",         // 60
        "backslash",           // 61
        "bracketright",        // 62
        "asciicircum",         // 63
        "underscore",          // 64
        "quoteleft",           // 65
        "a",                   // 66
        "b",                   // 67
        "c",                   // 68
        "d",                   // 69
        "e",                   // 70
        "f",                   // 71
        "g",                   // 72
        "h",                   // 73
        "i",                   // 74
        "j",                   // 75
        "k",                   // 76
        "l",                   // 77
        "m",                   // 78
        "n",                   // 79
        "o",                   // 80
        "p",                   // 81
        "q",                   // 82
        "r",                   // 83
        "s",                   // 84
        "t",                   // 85
        "u",                   // 86
        "v",                   // 87
        "w",                   // 88
        "x",                   // 89
        "y",                   // 90
        "z",                   // 91
        "braceleft",           // 92
        "bar",                 // 93
        "braceright",          // 94
        "asciitilde",          // 95
        "exclamdown",          // 96
        "cent",                // 97
        "sterling",            // 98
        "fraction",            // 99
        "yen",                 // 100
        "florin",              // 101
        "section",             // 102
        "currency",            // 103
        "quotesingle",         // 104
        "quotedblleft",        // 105
        "guillemotleft",       // 106
        "guilsinglleft",       // 107
        "guilsinglright",      // 108
        "fi",                  // 109
        "fl",                  // 110
        "endash",              // 111
        "dagger",              // 112
        "daggerdbl",           // 113
        "periodcentered",      // 114
        "paragraph",           // 115
        "bullet",              // 116
        "quotesinglbase",      // 117
        "quotedblbase",        // 118
        "quotedblright",       // 119
        "guillemotright",      // 120
        "ellipsis",            // 121
        "perthousand",         // 122
        "questiondown",        // 123
        "grave",               // 124
        "acute",               // 125
        "circumflex",          // 126
        "tilde",               // 127
        "macron",              // 128
        "breve",               // 129
        "dotaccent",           // 130
        "dieresis",            // 131
        "ring",                // 132
        "cedilla",             // 133
        "hungarumlaut",        // 134
        "ogonek",              // 135
        "caron",               // 136
        "emdash",              // 137
        "AE",                  // 138
        "ordfeminine",         // 139
        "Lslash",              // 140
        "Oslash",              // 141
        "OE",                  // 142
        "ordmasculine",        // 143
        "ae",                  // 144
        "dotlessi",            // 145
        "lslash",              // 146
        "oslash",              // 147
        "oe",                  // 148
        "germandbls",          // 149
        "onesuperior",         // 150
        "logicalnot",          // 151
        "mu",                  // 152
        "trademark",           // 153
        "Eth",                 // 154
        "onehalf",             // 155
        "plusminus",           // 156
        "Thorn",               // 157
        "onequarter",          // 158
        "divide",              // 159
        "brokenbar",           // 160
        "degree",              // 161
        "thorn",               // 162
        "threequarters",       // 163
        "twosuperior",         // 164
        "registered",          // 165
        "minus",               // 166
        "eth",                 // 167
        "multiply",            // 168
        "threesuperior",       // 169
        "copyright",           // 170
        "Aacute",              // 171
        "Acircumflex",         // 172
        "Adieresis",           // 173
        "Agrave",              // 174
        "Aring",               // 175
        "Atilde",              // 176
        "Ccedilla",            // 177
        "Eacute",              // 178
        "Ecircumflex",         // 179
        "Edieresis",           // 180
        "Egrave",              // 181
        "Iacute",              // 182
        "Icircumflex",         // 183
        "Idieresis",           // 184
        "Igrave",              // 185
        "Ntilde",              // 186
        "Oacute",              // 187
        "Ocircumflex",         // 188
        "Odieresis",           // 189
        "Ograve",              // 190
        "Otilde",              // 191
        "Scaron",              // 192
        "Uacute",              // 193
        "Ucircumflex",         // 194
        "Udieresis",           // 195
        "Ugrave",              // 196
        "Yacute",              // 197
        "Ydieresis",           // 198
        "Zcaron",              // 199
        "aacute",              // 200
        "acircumflex",         // 201
        "adieresis",           // 202
        "agrave",              // 203
        "aring",               // 204
        "atilde",              // 205
        "ccedilla",            // 206
        "eacute",              // 207
        "ecircumflex",         // 208
        "edieresis",           // 209
        "egrave",              // 210
        "iacute",              // 211
        "icircumflex",         // 212
        "idieresis",           // 213
        "igrave",              // 214
        "ntilde",              // 215
        "oacute",              // 216
        "ocircumflex",         // 217
        "odieresis",           // 218
        "ograve",              // 219
        "otilde",              // 220
        "scaron",              // 221
        "uacute",              // 222
        "ucircumflex",         // 223
        "udieresis",           // 224
        "ugrave",              // 225
        "yacute",              // 226
        "ydieresis",           // 227
        "zcaron",              // 228
        "exclamsmall",         // 229
        "Hungarumlautsmall",   // 230
        "dollaroldstyle",      // 231
        "dollarsuperior",      // 232
        "ampersandsmall",      // 233
        "Acutesmall",          // 234
        "parenleftsuperior",   // 235
        "parenrightsuperior",  // 236
        "twodotenleader",      // 237
        "onedotenleader",      // 238
        "zerooldstyle",        // 239
        "oneoldstyle",         // 240
        "twooldstyle",         // 241
        "threeoldstyle",       // 242
        "fouroldstyle",        // 243
        "fiveoldstyle",        // 244
        "sixoldstyle",         // 245
        "sevenoldstyle",       // 246
        "eightoldstyle",       // 247
        "nineoldstyle",        // 248
        "commasuperior",       // 249
        "threequartersemdash", // 250
        "periodsuperior",      // 251
        "questionsmall",       // 252
        "asuperior",           // 253
        "bsuperior",           // 254
        "centsuperior",        // 255
        "dsuperior",           // 256
        "esuperior",           // 257
        "isuperior",           // 258
        "lsuperior",           // 259
        "msuperior",           // 260
        "nsuperior",           // 261
        "osuperior",           // 262
        "rsuperior",           // 263
        "ssuperior",           // 264
        "tsuperior",           // 265
        "ff",                  // 266
        "ffi",                 // 267
        "ffl",                 // 268
        "parenleftinferior",   // 269
        "parenrightinferior",  // 270
        "Circumflexsmall",     // 271
        "hyphensuperior",      // 272
        "Gravesmall",          // 273
        "Asmall",              // 274
        "Bsmall",              // 275
        "Csmall",              // 276
        "Dsmall",              // 277
        "Esmall",              // 278
        "Fsmall",              // 279
        "Gsmall",              // 280
        "Hsmall",              // 281
        "Ismall",              // 282
        "Jsmall",              // 283
        "Ksmall",              // 284
        "Lsmall",              // 285
        "Msmall",              // 286
        "Nsmall",              // 287
        "Osmall",              // 288
        "Psmall",              // 289
        "Qsmall",              // 290
        "Rsmall",              // 291
        "Ssmall",              // 292
        "Tsmall",              // 293
        "Usmall",              // 294
        "Vsmall",              // 295
        "Wsmall",              // 296
        "Xsmall",              // 297
        "Ysmall",              // 298
        "Zsmall",              // 299
        "colonmonetary",       // 300
        "onefitted",           // 301
        "rupiah",              // 302
        "Tildesmall",          // 303
        "exclamdownsmall",     // 304
        "centoldstyle",        // 305
        "Lslashsmall",         // 306
        "Scaronsmall",         // 307
        "Zcaronsmall",         // 308
        "Dieresissmall",       // 309
        "Brevesmall",          // 310
        "Caronsmall",          // 311
        "Dotaccentsmall",      // 312
        "Macronsmall",         // 313
        "figuredash",          // 314
        "hypheninferior",      // 315
        "Ogoneksmall",         // 316
        "Ringsmall",           // 317
        "Cedillasmall",        // 318
        "questiondownsmall",   // 319
        "oneeighth",           // 320
        "threeeighths",        // 321
        "fiveeighths",         // 322
        "seveneighths",        // 323
        "onethird",            // 324
        "twothirds",           // 325
        "zerosuperior",        // 326
        "foursuperior",        // 327
        "fivesuperior",        // 328
        "sixsuperior",         // 329
        "sevensuperior",       // 330
        "eightsuperior",       // 331
        "ninesuperior",        // 332
        "zeroinferior",        // 333
        "oneinferior",         // 334
        "twoinferior",         // 335
        "threeinferior",       // 336
        "fourinferior",        // 337
        "fiveinferior",        // 338
        "sixinferior",         // 339
        "seveninferior",       // 340
        "eightinferior",       // 341
        "nineinferior",        // 342
        "centinferior",        // 343
        "dollarinferior",      // 344
        "periodinferior",      // 345
        "commainferior",       // 346
        "Agravesmall",         // 347
        "Aacutesmall",         // 348
        "Acircumflexsmall",    // 349
        "Atildesmall",         // 350
        "Adieresissmall",      // 351
        "Aringsmall",          // 352
        "AEsmall",             // 353
        "Ccedillasmall",       // 354
        "Egravesmall",         // 355
        "Eacutesmall",         // 356
        "Ecircumflexsmall",    // 357
        "Edieresissmall",      // 358
        "Igravesmall",         // 359
        "Iacutesmall",         // 360
        "Icircumflexsmall",    // 361
        "Idieresissmall",      // 362
        "Ethsmall",            // 363
        "Ntildesmall",         // 364
        "Ogravesmall",         // 365
        "Oacutesmall",         // 366
        "Ocircumflexsmall",    // 367
        "Otildesmall",         // 368
        "Odieresissmall",      // 369
        "OEsmall",             // 370
        "Oslashsmall",         // 371
        "Ugravesmall",         // 372
        "Uacutesmall",         // 373
        "Ucircumflexsmall",    // 374
        "Udieresissmall",      // 375
        "Yacutesmall",         // 376
        "Thornsmall",          // 377
        "Ydieresissmall",      // 378
        "001.000",             // 379
        "001.001",             // 380
        "001.002",             // 381
        "001.003",             // 382
        "Black",               // 383
        "Bold",                // 384
        "Book",                // 385
        "Light",               // 386
        "Medium",              // 387
        "Regular",             // 388
        "Roman",               // 389
        "Semibold",            // 390
    ];

    if (sid as usize) < SID_NAMES.len() {
        Some(SID_NAMES[sid as usize])
    } else {
        None
    }
}

/// Look up the SID for a standard glyph name by searching the predefined SID table.
pub(super) fn glyph_name_to_sid(name: &str) -> Option<u16> {
    for sid in 0u16..391 {
        if sid_to_name(sid) == Some(name) {
            return Some(sid);
        }
    }
    None
}

/// Annex D Table D.2 (MacRomanEncoding) byte → glyph name.
///
/// ASCII range 0x20-0x7E shares glyph names with WinAnsi; 0x80-0xFF is
/// the Mac OS Roman repertoire (which is *not* ISO-8859-1). The Apple-logo
/// glyph at 0xF0 (PUA U+F8FF) has no portable glyph name and returns `None`.
pub(super) fn mac_roman_byte_to_name(byte: u8) -> Option<&'static str> {
    use crate::fonts::font_dict::FontInfo;
    if (0x20..=0x7E).contains(&byte) {
        return FontInfo::gid_to_standard_glyph_name(byte as u16);
    }
    match byte {
        0x80 => Some("Adieresis"),
        0x81 => Some("Aring"),
        0x82 => Some("Ccedilla"),
        0x83 => Some("Eacute"),
        0x84 => Some("Ntilde"),
        0x85 => Some("Odieresis"),
        0x86 => Some("Udieresis"),
        0x87 => Some("aacute"),
        0x88 => Some("agrave"),
        0x89 => Some("acircumflex"),
        0x8A => Some("adieresis"),
        0x8B => Some("atilde"),
        0x8C => Some("aring"),
        0x8D => Some("ccedilla"),
        0x8E => Some("eacute"),
        0x8F => Some("egrave"),
        0x90 => Some("ecircumflex"),
        0x91 => Some("edieresis"),
        0x92 => Some("iacute"),
        0x93 => Some("igrave"),
        0x94 => Some("icircumflex"),
        0x95 => Some("idieresis"),
        0x96 => Some("ntilde"),
        0x97 => Some("oacute"),
        0x98 => Some("ograve"),
        0x99 => Some("ocircumflex"),
        0x9A => Some("odieresis"),
        0x9B => Some("otilde"),
        0x9C => Some("uacute"),
        0x9D => Some("ugrave"),
        0x9E => Some("ucircumflex"),
        0x9F => Some("udieresis"),
        0xA0 => Some("dagger"),
        0xA1 => Some("degree"),
        0xA2 => Some("cent"),
        0xA3 => Some("sterling"),
        0xA4 => Some("section"),
        0xA5 => Some("bullet"),
        0xA6 => Some("paragraph"),
        0xA7 => Some("germandbls"),
        0xA8 => Some("registered"),
        0xA9 => Some("copyright"),
        0xAA => Some("trademark"),
        0xAB => Some("acute"),
        0xAC => Some("dieresis"),
        0xAD => Some("notequal"),
        0xAE => Some("AE"),
        0xAF => Some("Oslash"),
        0xB0 => Some("infinity"),
        0xB1 => Some("plusminus"),
        0xB2 => Some("lessequal"),
        0xB3 => Some("greaterequal"),
        0xB4 => Some("yen"),
        0xB5 => Some("mu"),
        0xB6 => Some("partialdiff"),
        0xB7 => Some("summation"),
        0xB8 => Some("product"),
        0xB9 => Some("pi"),
        0xBA => Some("integral"),
        0xBB => Some("ordfeminine"),
        0xBC => Some("ordmasculine"),
        0xBD => Some("Omega"),
        0xBE => Some("ae"),
        0xBF => Some("oslash"),
        0xC0 => Some("questiondown"),
        0xC1 => Some("exclamdown"),
        0xC2 => Some("logicalnot"),
        0xC3 => Some("radical"),
        0xC4 => Some("florin"),
        0xC5 => Some("approxequal"),
        0xC6 => Some("Delta"),
        0xC7 => Some("guillemotleft"),
        0xC8 => Some("guillemotright"),
        0xC9 => Some("ellipsis"),
        0xCA => Some("space"), // nonbreakingspace; the canonical glyph name is "space"
        0xCB => Some("Agrave"),
        0xCC => Some("Atilde"),
        0xCD => Some("Otilde"),
        0xCE => Some("OE"),
        0xCF => Some("oe"),
        0xD0 => Some("endash"),
        0xD1 => Some("emdash"),
        0xD2 => Some("quotedblleft"),
        0xD3 => Some("quotedblright"),
        0xD4 => Some("quoteleft"),
        0xD5 => Some("quoteright"),
        0xD6 => Some("divide"),
        0xD7 => Some("lozenge"),
        0xD8 => Some("ydieresis"),
        0xD9 => Some("Ydieresis"),
        0xDA => Some("fraction"),
        0xDB => Some("currency"),
        0xDC => Some("guilsinglleft"),
        0xDD => Some("guilsinglright"),
        0xDE => Some("fi"),
        0xDF => Some("fl"),
        0xE0 => Some("daggerdbl"),
        0xE1 => Some("periodcentered"),
        0xE2 => Some("quotesinglbase"),
        0xE3 => Some("quotedblbase"),
        0xE4 => Some("perthousand"),
        0xE5 => Some("Acircumflex"),
        0xE6 => Some("Ecircumflex"),
        0xE7 => Some("Aacute"),
        0xE8 => Some("Edieresis"),
        0xE9 => Some("Egrave"),
        0xEA => Some("Iacute"),
        0xEB => Some("Icircumflex"),
        0xEC => Some("Idieresis"),
        0xED => Some("Igrave"),
        0xEE => Some("Oacute"),
        0xEF => Some("Ocircumflex"),
        0xF0 => None, // Apple-logo PUA glyph; no portable name
        0xF1 => Some("Ograve"),
        0xF2 => Some("Uacute"),
        0xF3 => Some("Ucircumflex"),
        0xF4 => Some("Ugrave"),
        0xF5 => Some("dotlessi"),
        0xF6 => Some("circumflex"),
        0xF7 => Some("tilde"),
        0xF8 => Some("macron"),
        0xF9 => Some("breve"),
        0xFA => Some("dotaccent"),
        0xFB => Some("ring"),
        0xFC => Some("cedilla"),
        0xFD => Some("hungarumlaut"),
        0xFE => Some("ogonek"),
        0xFF => Some("caron"),
        _ => None,
    }
}

/// Annex D Table D.1 (StandardEncoding, PostScript) byte → glyph name.
///
/// ASCII range 0x20-0x7E shares glyph names with WinAnsi except a handful
/// (0x27 quoteright, 0x60 quoteleft, etc.) — those overlap the existing
/// WinAnsi table's choice of `quoteright` for 0x27. The high-byte range
/// has its own PostScript repertoire (fraction at 0xA4, ligature `fi`/`fl`
/// at 0xAE/0xAF, etc.) which differs sharply from WinAnsi.
///
/// Bytes left unassigned by StandardEncoding return `None`.
pub(super) fn standard_encoding_byte_to_name(byte: u8) -> Option<&'static str> {
    use crate::fonts::font_dict::FontInfo;
    if (0x20..=0x7E).contains(&byte) {
        return FontInfo::gid_to_standard_glyph_name(byte as u16);
    }
    match byte {
        0xA1 => Some("exclamdown"),
        0xA2 => Some("cent"),
        0xA3 => Some("sterling"),
        0xA4 => Some("fraction"),
        0xA5 => Some("yen"),
        0xA6 => Some("florin"),
        0xA7 => Some("section"),
        0xA8 => Some("currency"),
        0xA9 => Some("quotesingle"),
        0xAA => Some("quotedblleft"),
        0xAB => Some("guillemotleft"),
        0xAC => Some("guilsinglleft"),
        0xAD => Some("guilsinglright"),
        0xAE => Some("fi"),
        0xAF => Some("fl"),
        0xB1 => Some("endash"),
        0xB2 => Some("dagger"),
        0xB3 => Some("daggerdbl"),
        0xB4 => Some("periodcentered"),
        0xB6 => Some("paragraph"),
        0xB7 => Some("bullet"),
        0xB8 => Some("quotesinglbase"),
        0xB9 => Some("quotedblbase"),
        0xBA => Some("quotedblright"),
        0xBB => Some("guillemotright"),
        0xBC => Some("ellipsis"),
        0xBD => Some("perthousand"),
        0xBF => Some("questiondown"),
        0xC1 => Some("grave"),
        0xC2 => Some("acute"),
        0xC3 => Some("circumflex"),
        0xC4 => Some("tilde"),
        0xC5 => Some("macron"),
        0xC6 => Some("breve"),
        0xC7 => Some("dotaccent"),
        0xC8 => Some("dieresis"),
        0xCA => Some("ring"),
        0xCB => Some("cedilla"),
        0xCD => Some("hungarumlaut"),
        0xCE => Some("ogonek"),
        0xCF => Some("caron"),
        0xE1 => Some("AE"),
        0xE3 => Some("ordfeminine"),
        0xE8 => Some("Lslash"),
        0xE9 => Some("Oslash"),
        0xEA => Some("OE"),
        0xEB => Some("ordmasculine"),
        0xF1 => Some("ae"),
        0xF5 => Some("dotlessi"),
        0xF8 => Some("lslash"),
        0xF9 => Some("oslash"),
        0xFA => Some("oe"),
        0xFB => Some("germandbls"),
        _ => None,
    }
}
